kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-auth-refresh
rules:
- apiGroups: ["*"]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-auth-refresh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ecr-auth-refresh
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ecr-auth-refresh
spec:
  template:
    metadata:
      labels:
        app: ecr-auth-refresh
    spec:
      containers:
      - image: jeffvader/ecr-auth-refresh:latest
        name: ecr-auth-refresh
        env:
          - name: AWS_DEFAULT_REGION
            value: eu-west-1
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ecr-auth-refresh-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ecr-auth-refresh-credentials
                key: AWS_SECRET_ACCESS_KEY
          - name: ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: ecr-auth-refresh-credentials
                key: ACCOUNT_ID